import os

DATABASE_ENDPOINT = os.environ.get("DATABASE_ENDPOINT")
DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD")
DATABASE_PORT = os.environ.get("DATABASE_PORT")
DATABASE_USERNAME = os.environ.get("DATABASE_USERNAME")
DATABASE_DBNAME = os.environ.get("DATABASE_DBNAME")

config = f"mysql+pymysql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_ENDPOINT}:{DATABASE_PORT}/{DATABASE_DBNAME}?charset=utf8mb4"