"""create table

Revision ID: 54bc1a27406a
Revises: 4fd16d32d727
Create Date: 2019-10-12 14:16:13.543356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bc1a27406a'
down_revision = '4fd16d32d727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DartReportList',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('issue_company', sa.String(length=60), nullable=True),
    sa.Column('issue_date', sa.String(length=10), nullable=True),
    sa.Column('report_link', sa.String(length=200), nullable=True),
    sa.Column('report_name', sa.String(length=60), nullable=True),
    sa.Column('disclosure_company', sa.String(length=60), nullable=True),
    sa.Column('report_id', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('DartReportType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=60), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=60), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DartReportType')
    op.drop_table('DartReportList')
    # ### end Alembic commands ###
