"""company list 추가

Revision ID: 6bb14b9abf5e
Revises: 54bc1a27406a
Create Date: 2019-10-15 22:28:10.873391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb14b9abf5e'
down_revision = '54bc1a27406a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DartCompanyList',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_korean_name', sa.String(length=255), nullable=True),
    sa.Column('company_english_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('market_ticker', sa.String(length=6), nullable=True),
    sa.Column('CEO', sa.String(length=50), nullable=True),
    sa.Column('company_type', sa.String(length=30), nullable=True),
    sa.Column('company_registration_number', sa.String(length=20), nullable=True),
    sa.Column('business_registration_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.Column('ir_url', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('fax', sa.String(length=30), nullable=True),
    sa.Column('business_type', sa.String(length=30), nullable=True),
    sa.Column('foundation_date', sa.String(length=30), nullable=True),
    sa.Column('settlement_month', sa.String(length=30), nullable=True),
    sa.Column('company_id', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.add_column('DartReportList', sa.Column('issue_company_id', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DartReportList', 'issue_company_id')
    op.drop_table('DartCompanyList')
    # ### end Alembic commands ###
